layout_spectrum: 0.05734767
typography_spectrum: 0.06272402
color:
  saturation: 0.8413103
  lightness: 0.7755333
  brandStrength: 0.3458781
  brandColors:
    - '#DAE3F2'
    - '#3A2F2D'
    - '#C6BEB3'
    - '#AD7B62'
    - '#835546'
  rhythmicContrast: 0.3491431
name: J+J_NZ_OCT1216
